language: python
  - '2.7'

dist: xenial

services:
  docker

before_script:
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - echo "script begin"

after_success:
  # 当代码测试通过后执行的命令
  - docker build -t alexueqing/superservice-product:latest .
  - docker push alexueqing/superservice-product:latest
