language: python
  - '2.7'

dist: xenial

services:
  docker

before_script:
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - echo "script begin"
  - docker ps | grep -q blog

after_success:
  # 当代码测试通过后执行的命令
  - docker build -t superservice/product-service-py .
  - docker push superservice/product-service-py
